# Generated by Django 6.0.1 on 2026-01-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_organization_reader_token'),
        ('main', '0003_student_middle_name_student_organization_event_and_more'),
    ]

    operations = [
    ]
